export default {
  purple: '#DDD2FD',
  mainpurple: '#C8BCEC',
  blue: '#DEECED',
  mainblue: '#C9DDDC',
  sky: '#dde0ec',
  mainsky: '#c9cbdd',
  green: '#DEECDD',
  maingreen: '#C3DEC1',
  orange: '#F9E9C8',
  mainorange: '#EDDAB3',
  background: '#FDE8C9',
  black: '#131414',
  grey: '#A7A6A6',
  white: '#FFFDFC',
  darkbackground: '#B5A691',
}
