export default {
  en: {
    // settings screen
    language: 'Language',
    // main screen
    yourTaskMahager: 'Your Task Manager',
    January: 'January',
    February: 'February',
    March: 'March',
    April: 'April',
    May: 'May',
    June: 'June',
    July: 'July',
    August: 'August',
    September: 'September',
    October: 'October',
    November: 'November',
    December: 'December',
    tasksLeft: 'tasks left',
    discussYourGoalsWithOthers: 'Discuss your goals with others',
    chat: 'chat',
    Account: 'Account',
    Settings: 'Settings',
    // todo screen
    YourTaskList: 'Your Task List',
    writtenBy: 'written by',
    doneBy: 'done by',
    AddNewTask: 'Add new task',
    placeholder: 'start typing a task',
  },
  ua: {
    // settings screen
    language: 'Мова',
    // main screen
    yourTaskMahager: 'Менеджер задач',
    January: 'Січень',
    February: 'Лютий',
    March: 'Березень',
    April: 'Квітень',
    May: 'Травень',
    June: 'Червень',
    July: 'Липень',
    August: 'Серпень',
    September: 'Вересень',
    October: 'Жовтень',
    November: 'Листопад',
    December: 'Грудень',
    tasksLeft: 'задач лишилось',
    discussYourGoalsWithOthers: 'Спількуйтеся з усіма у чаті',
    chat: 'чат',
    Account: 'Профіль',
    Settings: 'Налаштування',
    // todo screen
    YourTaskList: 'Список задач',
    writtenBy: 'написано',
    doneBy: 'зроблено',
    AddNewTask: 'Додати задачу',
    placeholder: 'почніть вводити задачу',
  },
}
